import Config

# Configure your database
config :leythers_com, LeythersCom.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "leythers_com_dev",
  prepare: :unnamed,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :leythers_com, LeythersComWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "9dwItTb5W0sC1DUQ9yh/kZwZ2AzgORLP9gydSvGB5VOkkQaZ+8PLu3xZLPMja9M4",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:leythers_com, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:leythers_com, ~w(--watch)]}
  ]

# LLM configuration for development
# Allow longer timeouts for local Ollama since it may be slower on first request
config :leythers_com,
  llm_comparison_timeout_ms: 60_000

# In dev, run intelligence jobs one-at-a-time so LLM calls queue naturally.
config :leythers_com, Oban, queues: [intelligence: 1]

# Use a gradual circuit cooldown ramp for local Ollama to avoid burst/recover churn.
config :leythers_com, :llm_guard,
  open_cooldown_min_ms: 1_500,
  open_cooldown_step_ms: 1_500,
  open_cooldown_max_ms: 20_000

config :leythers_com, :llm_rate_limit,
  enabled: true,
  key: "llm:dev",
  scale_ms: 1_000,
  limit: 2,
  max_wait_ms: 30_000

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :leythers_com, LeythersComWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/leythers_com_web/router\.ex$"E,
      ~r"lib/leythers_com_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :leythers_com, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Keep editorial processing practical in development: avoid extra LLM grouping
# calls and keep each worker run bounded for faster visible progress.
config :leythers_com, :intelligence_generation,
  llm_grouping_enabled: false,
  grouping_llm_timeout_ms: 30_000,
  source_batch_size: 8,
  max_batches_per_run: 8,
  source_editorial_retry_base_seconds: 1,
  source_editorial_retry_max_seconds: 8,
  source_editorial_retry_persist_threshold: 3

config :leythers_com, :editorial_orchestration,
  refresh_retry_base_seconds: 1,
  refresh_retry_max_seconds: 8,
  refresh_retry_persist_threshold: 3

# LLM configuration for development
# Allow longer timeouts for local Ollama since it may be slower on first request
# and can have variable performance. Production defaults to 3 seconds.
config :leythers_com,
  llm_comparison_timeout_ms: 60_000
